Tangled C code.
'gcc -c main.c' produces the (expected) error message

./sub1.h:2:13: error: ‘TEST’ undeclared here (not in a function)
 int unused = TEST;
             ^

with the correct '#line' directive (both line number and file name).